_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.7
            "5": 0.19.2
            "8":
                - 1
                - 5
            "12": 0.19.2
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
hdim:
    value: 256
latent_dim:
    value: 64
lr:
    value: 0.0005
nb_critic:
    value: 5
nb_layers:
    value: 2
selected_categories:
    value:
        - dataset
